### ISSUE TITLE
能否支持测试版打包？

### ISSUE THREAD

**Issue by Logan676** [mcxiaoke/packer-ng-plugin#10]
由于我的需求要求打出的正式版APK和测试版APK使用的服务器地址和其他一些配置都不同，所以需要打两种类型的APK，但是`gradlew tasks`运行后显示的Task列表中只有apkRelease，没有发现apkDebug。即便新增一个build type `beta`然后把debug这个build type下的配置copy过去，运行apkBeta打出的包仍然是release版。

请问这个工具支持打测试版的APK吗？应该如何配置。
我的配置如下
![image](https://cloud.githubusercontent.com/assets/2975850/13628103/434bb1f6-e60a-11e5-8fb4-a44e162c029e.png)

app/build.gradle如下：
```
 buildTypes {
        debug {
            debuggable true
            // 将debug版本的包名设置为<app package>.debug以便能够同时在一台设备上安装debug和release版本的apk
            applicationIdSuffix ".debug"
            minifyEnabled false
            //zipAlignEnabled true
            //shrinkResources true
            signingConfig signingConfigs.debug
            buildConfigField("boolean", "LOG_DEBUG", "true")//是否输出LOG信息
            buildConfigField("String", "SERVER", "\"${test_server}\"")
        }

        release {
            debuggable false
            // 移除无用的resource文件
            // shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            buildConfigField("boolean", "LOG_DEBUG", "false")
            buildConfigField("String", "SERVER", "\"${product_server}\"")
        }
    }
```

**Comment by mcxiaoke** [comment]
是支持的，你用 ./gradlew apkBeta就行了， README有详细的说明，但这种需求其实更适合用productFlavors 解决

**Comment by Logan676** [comment]
是的，以前用的打包方式就是productFlavors方式，能够打包出debug版，但是二十几个包需要十几分钟时间。但是试了几次beta打出的包并不是我想要的测试版。

我的打包需求是分别打包出测试版（内部测试用）和正式版，测试版的包名，launcher icon，服务器地址等和正式版都不同。从上面的截图可以看出我把测试版的配置放在了`debug`目录下。但是运行beta的任务并没有读取里面的内容。`BuildConfig.DEBUG`也没有被置换。

**Comment by mcxiaoke** [comment]
你用apkRelease打出的就是release包，用apkBeta打出的就是beta包，和你正常使用 ./gradlew assembleBeta和assembleBeta打出的包是一样的，你可以先试试 assembleXXX这种看配置对不对

**Comment by Logan676** [comment]
assembleBeta应该是对的，确切的说我用的是`assembleDebug`，打出的包是正确的。但是apk的存放路径是`app/build/output/apk`，和这个工具指定的路径不同。而且打包速度慢。

**Comment by mcxiaoke** [comment]
这个工具是用于渠道包输出的，所以会忽略buildType=debug配置

**Comment by Logan676** [comment]
有可能支持测试版的渠道包输出吗？

**Comment by mcxiaoke** [comment]
是支持的，我上面都提到了怎么做，README的说明也可以再看看
