### ISSUE TITLE
absolutePath' on null object？

### ISSUE THREAD

**Issue by yanglichuan** [mcxiaoke/packer-ng-plugin#101]
============================================================
PackerNg - https://github.com/mcxiaoke/packer-ng-plugin
============================================================
:app:apkRelease FAILED          
              
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:apkRelease'.
> Cannot get property 'absolutePath' on null object

**Comment by 601367322** [comment]
up
