### ISSUE TITLE
增加渠道信息需要放在APK处理过程的最后一步？

### ISSUE THREAD

**Issue by yanglichuan** [mcxiaoke/packer-ng-plugin#102]
您好
感谢您的分享
我想问下    加固在前    还是增加渠道信息在前 

增加渠道信息需要放在APK处理过程的最后一步  这句话 什么意思啊

**Comment by mcxiaoke** [comment]
要在V2签名之后，见 https://github.com/mcxiaoke/packer-ng-plugin/issues/86
