### ISSUE TITLE
希望多渠道打包能重新用最新的gradle编译下

### ISSUE THREAD

**Issue by baoziguo** [mcxiaoke/packer-ng-plugin#103]
把android studio升级到了3.0，同时gradle也升级最新的了，希望多渠道打包能重新用最新的gradle编译下！！！

**Comment by huyongqiang** [comment]
现在还不支持android studio 3.0吧？
Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
         https://oss.sonatype.org/content/repositories/snapshots/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
......

**Comment by mcxiaoke** [comment]
这个编译用的版本和你项目用的版本没关系
