### ISSUE TITLE
android studio 3.0 打包不行了

### ISSUE THREAD

**Issue by OvenCroc** [mcxiaoke/packer-ng-plugin#104]
之前2.3.2都是可以的 , 最近出了3.0 我就更新了 然后gradlew clean apkRelease 就不成功了, 每次都报APK Signature Scheme v2 verify failed: 'D:\zhoupan\github_project\weather_as\cmweather_v4.3.3_newonline\build\outputs\apk\cmweather_v4.3.3_newonline-release-unsigned.apk'这个错 有没有好的解决办法?

**Comment by mcxiaoke** [comment]
V2版只支持APK Signature Scheme v2，要求在 signingConfigs 里 v2SigningEnabled true 启用新版签名模式
