### ISSUE TITLE
Confict with Realm 4.3.0~4.3.1

### ISSUE THREAD

**Issue by jy02050803** [mcxiaoke/packer-ng-plugin#109]
Error:(300, 0) Unable to load class 'com.android.builder.Version'.
with (apply plugin: 'packer')

**Comment by jy02050803** [comment]
it is a realm's bug
Link: https://github.com/realm/realm-java/issues/5640
Close this one

**Comment by Zhuinden** [comment]
See https://github.com/realm/realm-java/issues/5640#issuecomment-355497076
