### ISSUE TITLE
集成打包和脚本打包都跑不通

### ISSUE THREAD

**Issue by 601367322** [mcxiaoke/packer-ng-plugin#110]
> Task :app:apkProdRelease
============================================================
PackerNg - https://github.com/mcxiaoke/packer-ng-plugin
============================================================

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:apkProdRelease'.
> Cannot get property 'absolutePath' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 4s
1068 actionable tasks: 262 executed, 718 from cache, 88 up-to-date

bingbingdeMacBook-Pro:tengyue-android bingbing$ java -jar packer-ng-2.0.0.jar generate --channels=@markets_360.txt --output=./ app-release.apk 
========== APK Packer ==========
Error: Invalid Signature: app-release.apk

**Comment by 601367322** [comment]
classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by 601367322** [comment]
compileSdkVersion = 26//编译版本
  buildToolsVersion = "26.0.2"//编译工具版本

**Comment by 601367322** [comment]
packer {
    archiveNameFormat = '${buildType}-v${versionName}-${channel}'
    archiveOutput = new File(project.rootProject.buildDir, "apks")
    channelMap = [
            "All" : project.rootProject.file("markets.txt"),
    ]
}

**Comment by 601367322** [comment]
./gradlew clean apkProdRelease

**Comment by 601367322** [comment]
signingConfigs {

        release {
            keyAlias props['KEY_ALIAS']
            keyPassword props['KEY_PASSWORD']
            storeFile file(props['KEYSTORE_FILE'])
            storePassword props['KEYSTORE_PASSWORD']

            v2SigningEnabled true
        }
    }

**Comment by 601367322** [comment]
用walle就可以了。

**Comment by mcxiaoke** [comment]
还未在 `com.android.tools.build:gradle:3.0.1` 下测试，可能不支持

**Comment by Dev-Wiki** [comment]
遇到同样为题, 无论怎么设置文件路径 都有此问题

我就是想解决不同flavor 的不同渠道问题
