### ISSUE TITLE
No such property: flavorName for class: SimpleTemplateScript1

### ISSUE THREAD

**Issue by xingjiyuan** [mcxiaoke/packer-ng-plugin#113]
命令打包没问题，但是gradle打包时报错

输出信息：

    :XXXXXX:validateSigningRelease
    :XXXXXX:packageRelease
    :XXXXXX:assembleRelease
    :XXXXXX:apkRelease
    ============================================================
    PackerNg - https://github.com/mcxiaoke/packer-ng-plugin
    ============================================================
    Variant: release
    Input: XXXXXX.apk
    Output: /XXXXXX/channels
    Channels: [XXXXXX1 XXXXXX2 XXXXXX3]
    :XXXXXX:apkRelease FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':moer_finance:apkRelease'.
    > No such property: flavorName for class: SimpleTemplateScript1

gradle插件版本2.2.3

**Comment by mcxiaoke** [comment]
https://github.com/mcxiaoke/packer-ng-plugin/issues/82
