### ISSUE TITLE
关于debug版本的打包问题

### ISSUE THREAD

**Issue by luoxiaohui** [mcxiaoke/packer-ng-plugin#114]
你好，我在打包时想区分测试和生产环境，所以会在gradle文件中buildTypes里的debug和release部分配置一些参数。我用./gradlew clean apkRelease是读取的release下面的参数，但是我用.gradlew clean apkDebug却不能读取debug部分下面的参数，它还是读的release部分的参数。
请教下，我应该用什么命令才能读取debug部分参数并打包呢?

**Comment by luoxiaohui** [comment]
补充一下，我刚刚试过了，在主module中配置buildTypes中debug和release参数是能读取到的，但是由于我项目中有多个module，一般app域名等其他配置参数是放在base module中，这时候执行./gradlew clean apkDebug是获取不了base module中buildTypes中里的参数的，这个有办法解决的吗？

**Comment by mcxiaoke** [comment]
打包插件不干涉Android构建过程
