### ISSUE TITLE
V1签名多渠道方案在PP助手增量更新时失效问题

### ISSUE THREAD

**Issue by chiangchangjun** [mcxiaoke/packer-ng-plugin#115]
作者好，V1签名下，使用 zip comment 进行渠道号的写入，在PP助手的增量更新下，zip comment 部分的数据会被丢弃，不知道作者有没有遇到，或者有什么应对方案？
另外，我们暂未使用V2签名，不知道V2签名下，有没有类似的问题（sign Block区域自定义信息丢失）？

**Comment by mcxiaoke** [comment]
不清楚你说的增量更新的技术细节，但V2应该也会有类似的问题，你可以读取后保存渠道号到SharedPreferences，或者尝试一下其它的方案
