### ISSUE TITLE
java.lang.NoClassDefFoundError: com.mcxiaoke.packer.helper.PackerNg$Helper

### ISSUE THREAD

**Issue by JayZhaoBoy** [mcxiaoke/packer-ng-plugin#117]
final String channel = PackerNg.getMarket(this);
在Application onCreate中初始化，在android api19的魅族手机上报错了，在我的其他6.0， 8.0系统都是正常的。原本我是在activity中初始化的，但是我发现umeng在初始化的时候会就会自动去寻找原本应该定义在productFlavors中的渠道，现在换了获取渠道字符串的方式，而umeng会默认第一次加载的渠道是有效的，所以出现大量unknown渠道。所以上述方法只能在activity中使用么？使用版本是1.0.9

**Comment by mcxiaoke** [comment]
1. 在Application用没问题，你检查一下是不是Proguard或其它原因造成的；2. umeng统计有代码设置渠道的方法

**Comment by JayZhaoBoy** [comment]
在我的另外两个手机都是正常的，而且在debug模式下没有开混淆依然不行诶，我把这行代码放在application中onCreate的第一行，所以就只有这一个报错log

**Comment by JayZhaoBoy** [comment]
很奇怪我把代码往后移动了几行，就可以了，难道在某些机型加载太早找不到这个类么？【苦笑】

**Comment by mcxiaoke** [comment]
所有的业务代码都需要放在 `super.onCreate()` 后面

**Comment by JayZhaoBoy** [comment]
是在super.onCreate()之后的第一行，我只是往后移动了几行。虽然我的问题解决了，但不知道啥原因导致的。不过你有兴趣可以实际实验一下找找原因，魅族的max4 pro 系统版本是4.4.4（哈哈当然也有可能是单个手机的bug）。 使用的是1.0.9版本的框架。
