### ISSUE TITLE
渠道打包之后如何验证

### ISSUE THREAD

**Issue by fuqile** [mcxiaoke/packer-ng-plugin#121]
我使用360加固后，使用build-tools下面的zipalign和apksigner进行v2签名后，最后使用packer-ng命令对签名后的包加入渠道，但是这个包在使用后好像一直都统计不到信息，用的是友盟的统计。
我想问一下渠道包打出来只要如何验证是否已经成功

**Comment by fuqile** [comment]
verify的结果是
Error: No APK Signing Block before ZIP Central Directory

**Comment by fuqile** [comment]
使用apksigner  verify的结果是
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Number of signers: 1
WARNING: META-INF/android.arch.lifecycle_runtime.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_animated-vector-drawable.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_appcompat-v7.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_cardview-v7.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_design.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_recyclerview-v7.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_support-compat.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_support-core-ui.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_support-core-utils.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_support-fragment.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_support-media-compat.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_support-v4.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_support-vector-drawable.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/com.android.support_transition.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/

**Comment by fuqile** [comment]
刚刚测试了一下，直接用 gradle build出来的包，使用apksigner verify的结果和上面的一致，通过packer-ng命令添加渠道之后再用packer-ng verify是对的
是不是针对360加固的问题无法完美适配

**Comment by mcxiaoke** [comment]
我用360加固测试了，完全没有问题：

360加固后用apksigner签名的文件：
```
java -jar tools/packer-ng-2.0.0.jar verify jiagu360_signed.apk
========== APK Verify ==========
File: jiagu360_signed.apk
Signed: true
Channel: null
```
签名后用PackerNg打包后的文件
```
java -jar tools/packer-ng-2.0.0.jar verify output/jiagu360_signed-ch1.apk
========== APK Verify ==========
File: jiagu360_signed-ch1.apk
Signed: true
Channel: ch1
```

注意：plugin 和 helper 的版本号需要保持一致，都用2.0.0版

**Comment by fuqile** [comment]
可能是我之前的包打的有问题，后来我再试了一下是好的。麻烦了，感谢！
我整理了一个加固后的自动签名打包脚本，可以看一下
https://github.com/fuqile/packer-ng-reinforce

**Comment by yushilong** [comment]
1.9.0的怎么验证？
