### ISSUE TITLE
请问贵插件对v1和v2两种签名方式是怎么兼容支持的?

### ISSUE THREAD

**Issue by zengcanxiang** [mcxiaoke/packer-ng-plugin#122]
由于v2签名方式在Android 7.0才支持,在7.0以前的系统都是验证v1方式,所以之前我们打包都是v1和v2都支持.

在文档一开始我看到说只支持v2方式,有点疑惑,那么这样的包在Android 7.0以前不是安装不了么?

**Comment by mcxiaoke** [comment]
这个与本项目无关，看Android官方文档，V2签名是在V1签名的基础上进行的，7.0之前不验证V2签名部分

**Comment by cfJand** [comment]
我也有这个疑惑，看项目说明只支持V2签名，虽然作者说7.0之前不验证V2签名，但是并没有说明是否对7.0以前的进行兼容性的V1签名操作？

**Comment by mcxiaoke** [comment]
V2签名包含V1签名
