### ISSUE TITLE
AS3.1.2版本Gradle4.4 用不了

### ISSUE THREAD

**Issue by liujiwei5018** [mcxiaoke/packer-ng-plugin#124]
不能使用apply plugin: 'packer'
加这行代码 就报错
如何解决？大佬们

**Comment by liujiwei5018** [comment]
之前在AS2.3.3版本上可以使用，手贱升级as之后就。。。。。。。。。。

**Comment by mcxiaoke** [comment]
使用最新的v2.0.1，支持Gradle 4.x + Android Plugin 3.x

**Comment by liujiwei5018** [comment]
好的,可能我的配置有问题

**Comment by liujiwei5018** [comment]
//gradlew clean apkRelease    输出所有渠道包 命令行
packer {
    archiveNameFormat = '${appPkg}-${buildType}-v${versionName}-${channel}'
    archiveOutput = new File(project.rootProject.buildDir, "apks")

    channelFile = project.rootProject.file("channel.txt")

}
archiveNameFormat   这里面如何加上打包日期时间?

**Comment by mcxiaoke** [comment]
@liujiwei5018 https://stackoverflow.com/questions/19172565/how-append-date-build-to-versionnamesuffix-on-gradle
