### ISSUE TITLE
No such property: flavorName for class: SimpleTemplateScript11

### ISSUE THREAD

**Issue by luxianyue** [mcxiaoke/packer-ng-plugin#125]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:apkAaaaaaRelease'.
> No such property: flavorName for class: SimpleTemplateScript11

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by mcxiaoke** [comment]
flavorName -> flavor
