### ISSUE TITLE
对于极光统计，渠道是写在manifestPlaceholders里怎么处理呀

### ISSUE THREAD

**Issue by welkinwong** [mcxiaoke/packer-ng-plugin#126]
hello，
求帮助

极光统计的渠道名称是写在`build.gradle`下的`manifestPlaceholders`里的
```
    defaultConfig {
        manifestPlaceholders = [
            JPUSH_APPKEY: "key",
            APP_CHANNEL : "official"
        ]
    }
```

这种情况怎么使用packer-ng-plugin呢

PS：我是用v1旧版的packer-ng-plugin

**Comment by mcxiaoke** [comment]
用这个  https://github.com/mcxiaoke/gradle-packer-plugin 或者看极光的文档，一般都提供了代码设置渠道的方法

**Comment by welkinwong** [comment]
极光统计似乎没有提供代码设置渠道的方法，是不是就不可以用了囧
