### ISSUE TITLE
建议 packer 配置属性里添加 market文件路径

### ISSUE THREAD

**Issue by xiaoooyu** [mcxiaoke/packer-ng-plugin#13]
packer {
        // 指定渠道打包输出目录
        // archiveOutput = file(new File(project.rootProject.buildDir.path, "archives"))
        // 指定渠道打包输出文件名格式
        // 默认是 `${appPkg}-${flavorName}-${buildType}-v${versionName}-${versionCode}`
        // archiveNameFormat = '${appPkg}-${flavorName}-${buildType}-v${versionName}-${versionCode}‘
        market = '${rootProject}/market.txt'
}

**Comment by zpetter** [comment]
* What went wrong:
Execution failed for task ':trunk:processHelloReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'F:\new\android-sdk\android-sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1

**Comment by mcxiaoke** [comment]
默认就是 market = '${rootProject}/market.txt'，如果需要自定义请命令行参数指定
