### ISSUE TITLE
多渠道不同资源文件的打包不支持吗？

### ISSUE THREAD

**Issue by ChenViVi** [mcxiaoke/packer-ng-plugin#135]
像是这种形式的资源替换，直接执行打包命令 gradle apkRelease，发现没有根据渠道不同而使用不同的资源文件，是这个插件不支持还是我的打开方式有问题？

![](http://img.valorachen.top/18-9-26/74187916.jpg)

**Comment by mcxiaoke** [comment]
不支持，这里的渠道不是gradle里的flavor，这个支持 https://github.com/mcxiaoke/gradle-packer-plugin
