### ISSUE TITLE
Error: Invalid Signature

### ISSUE THREAD

**Issue by jacksPeak** [mcxiaoke/packer-ng-plugin#138]
执行流程：
1、百度加固
2、使用此命令签名：jarsigner -verbose -keystore [keystorePath] -signedjar [apkOut] [apkIn] [alias] -digestalg SHA1
3、使用此命令打渠道信息：packer-ng generate --channels=@channels.txt --output=build/archives app.apk

执行异常：
Error: Invalid Signature: /Users/anonymous/Desktop/release/v1.2.2/xxx.apk

**Comment by mcxiaoke** [comment]
第二步不对，V2签名的方法见这里  https://developer.android.com/studio/command-line/apksigner , --v2-signing-enabled 而且需要用zipalign对齐

**Comment by mcxiaoke** [comment]
1. zipalign -v -p 4 my-app-unsigned.apk my-app-unsigned-aligned.apk
2. apksigner sign --ks my-release-key.jks --out my-app-release.apk my-app-unsigned-aligned.apk
3. packer-ng generate --channels=@channels.txt --output=build/archives app.apk

ref: https://developer.android.com/studio/publish/app-signing

**Comment by mcxiaoke** [comment]
看特别提示： https://github.com/mcxiaoke/packer-ng-plugin#%E7%89%B9%E5%88%AB%E6%8F%90%E7%A4%BA

**Comment by jacksPeak** [comment]
非常感谢。就是第二步出了问题签名方式不对..
