### ISSUE TITLE
是否可以提供packer-ng-2.0.1.jar的原工程代码， 可以让开发者更加扩展打包功能

### ISSUE THREAD

**Issue by liuyuttkx** [mcxiaoke/packer-ng-plugin#140]
使用场景： 同一份代码， 生成不同包名，不同主题等的马甲包， 每个马甲包需要生成的渠道包也不一样。
请楼主开放packer-ng-2.0.1.jar原工程，这样开发者就可以根据自己的需求，开发出适合自己的工具。以上述为例，可以根据不同的马甲包，生成对应的渠道包，并放至指定的文件目录下。减少生成渠道包出错和打包时间。
建议： 在生成的多渠道包中，除了通过channles.txt文件设置渠道名以外， 我们还需要获取其它信息，比如渠道号，渠道别名等等。 建议可以给多渠道包设置多个参数值，不仅仅是设置渠道名。

**Comment by mcxiaoke** [comment]
本项目不就是源码吗
