### ISSUE TITLE
什么时候读取APK的注释

### ISSUE THREAD

**Issue by linsea** [mcxiaoke/packer-ng-plugin#17]
你好，谢谢你提供这么强大的打包工具。
有个细节问题我想问下，就是读取APK文件注释以解析出渠道号的过程，这个过程在用户安装APK之前还是之后？如果是前者，那么应用还没有安装，解析代码肯定还不能执行吧？如果是后者，那么应用安装完成后，APK已与应用无关了，甚至用户在启动应用之前已经删除了APK，那还怎么去读取解析它呢？

**Comment by mcxiaoke** [comment]
安装之后，读取的是应用自身的apk中的注释，安装后系统中会有一份apk的

**Comment by linsea** [comment]
@mcxiaoke 现在很多手机，如华为，安装应用后，系统弹出框提示应用安装了，要不要删除安装包，如果用户选择是，那是否就读不到了。另外，如果应用第一次启动之前，用户就删除安装包，是不是也就读不到渠道号了？

**Comment by mcxiaoke** [comment]
安装后系统会有一份应用对应的apk保存在某个目录，不是安装包那个apk

**Comment by linsea** [comment]
@mcxiaoke 哦， 你是指例如/data/app目录下的apk副本吧？
