### ISSUE TITLE
markets.txt支持key-value形式

### ISSUE THREAD

**Issue by wenjiahui** [mcxiaoke/packer-ng-plugin#19]
因为公司要求，上架商店的app，渠道id必须换成特殊的id，譬如360=1000a，就是说上架360商店的渠道id是1000a。因此希望market.txt支持该种方式打包，这样子打包的时候可以显示360.

**Comment by mcxiaoke** [comment]
@wenjiahui 打包的过程其实不需要关注，维护一份对应关系的表格，类似于这样用注释就能满足需求了吧？
```
1000a #360
1001a # baidu
```

**Comment by wenjiahui** [comment]
目前我使用的打包命名方式是app-${flavorName}-${buildType}-v${versionName}, 如果采取你的建议方案，命名就变成app-1000a-release-v1.0，而不是app-360-release-v1.0. 这样子上架商店的时候还要对照一次，感觉有点麻烦。不过还是谢谢你做了一个这么棒的库，已经节省不少时间了。

**Comment by mcxiaoke** [comment]
@wenjiahui 这个工具有不少人在用，为了保持兼容，目前不太方便改market文件的格式。看你的描述好像只是文件名的问题，建议写个简单的Shell或Python脚本，批量替换一下。

简单的写了一个脚本，你可以根据需要修改：<https://gist.github.com/mcxiaoke/df8d9c3f39f1a031a31dea3cf2a21cd9>

**Comment by wenjiahui** [comment]
非常感谢你这个脚本，已经用上了。  不过我用python3执行的时候报29行出错，`AttributeError: 'dict' object has no attribute 'iteritems'` ，我换成`for k,v in table.items()`就没问题了。

**Comment by mcxiaoke** [comment]
@wenjiahui 我这个是按照Python 2的语法写的，用Python 3可能需要微调，比如future的import不需要了
