### ISSUE TITLE
apkDebug not find

### ISSUE THREAD

**Issue by Heart2009** [mcxiaoke/packer-ng-plugin#22]
./gradlew -Pmarket=markets.txt apkDebug
提示：
Task 'apkDebug' not found in root project 'xxxxxx'

**Comment by kevin1202** [comment]
这个是怎么解决的？

**Comment by mcxiaoke** [comment]
代码里判断了忽略 debug 的 buildType，这个工具是用作渠道发布的

**Comment by kevin1202** [comment]
好的，知道了，非常感谢
