### ISSUE TITLE
和微信打包怎么配合？

### ISSUE THREAD

**Issue by vihuela** [mcxiaoke/packer-ng-plugin#25]
gradlew resguard
gradlew -Pmarkrt=markets.txt clean apkRelease
请问怎么一起生效？这块语法不怎么懂

**Comment by mcxiaoke** [comment]
可以先用微信的打包工具，然后使用PackerNg的Python打包脚本

1. ./gradlew resgurad 得到apk，假设apk为 someapp.apk
2. python ngpacker.py someapp.apk markets.txt  output_dir

参考这里 <https://github.com/mcxiaoke/packer-ng-plugin#命令行打包脚本>

**Comment by vihuela** [comment]
@mcxiaoke 

> F:\code\pack>python ngpacker.py target.apk markets.txt c:\
Traceback (most recent call last):
  File "ngpacker.py", line 12, in <module>
    from apkinfo import APK
  File "F:\code\pack\apkinfo.py", line 306
    except Exception, e:
                    ^
SyntaxError: invalid syntax

python环境装了，执行出现这个，不熟悉python语法，是哪里错了么？？

**Comment by mcxiaoke** [comment]
需要 Python 2，你用的是Python 3?

如果还不行，可以试试Java版

```
java -jar ngpacker-1.0.4-capsule.jar someapp.apk markets.txt 
```

**Comment by vihuela** [comment]
对的，我的是python3，可以了谢谢你！谢谢你

**Comment by mcxiaoke** [comment]
fixed
