### ISSUE TITLE
建议添加mapping等文件也输出到指定目录

### ISSUE THREAD

**Issue by shibenli** [mcxiaoke/packer-ng-plugin#27]
对于一些添加混淆的，这种输出文件还是比较有用的（建议：添加输出文件类型的配置）

**Comment by mcxiaoke** [comment]
你说的与此项目无关，packer-ng并不参与build过程，不会修改apk文件的内容，只会增加注释

**Comment by shibenli** [comment]
我的意思是添加一些文件拷贝的操作，对build结果的拷贝
