### ISSUE TITLE
加固会不会让渠道信息丢失呢

### ISSUE THREAD

**Issue by shibenli** [mcxiaoke/packer-ng-plugin#30]
国内一些渠道需要所谓的加固，这种方式的渠道信息会不会在使用加固之后的包中丢失了

**Comment by shibenli** [comment]
已经确定加固会导致渠道信息丢失，建议提供从不包含渠道的apk添加渠道信息的方法，加固之后手动加入渠道信息

**Comment by mcxiaoke** [comment]
PackerNg提供了脚本，你可以直接使用命令行工具，见 <https://github.com/mcxiaoke/packer-ng-plugin#命令行打包脚本>

**Comment by shibenli** [comment]
好迅速啊，我刚想回来说，找到命令行工具再手动加入渠道信息的。

**Comment by shibenli** [comment]
不过建议更新readme文档，说明加固等二次打包操作会破坏渠道信息，并提供对应的解决方案(虽然只要看懂了你的原理的人应该会知道。)
