### ISSUE TITLE
无法通过 Android 7.0 APK Signature Scheme v2 验证

### ISSUE THREAD

**Issue by dkmeteor** [mcxiaoke/packer-ng-plugin#31]
Failed to install xxxx.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1493827856.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]

目前只能在配置中关闭该配置
v2SigningEnabled false

**Comment by mcxiaoke** [comment]
你试一下不使用packer打包，看能不能通过验证？因为看报错信息是没有签名

**Comment by dkmeteor** [comment]
@mcxiaoke 
1. "v2SigningEnabled false" + packer 可通过
2. "v2SigningEnabled true" + 不用packer 可通过
3. "v2SigningEnabled true" + packer 无法通过

Android Studio 2.2+ v2SigningEnabled 不配置时默认是true.

ps.以前美团那套往apk里写{$channel名}.txt 的方案也无法通过该验证.

---
流程:
新建一个空project -> build -> 安装apk -> 成功
用 `java -jar ngpacker-1.0.4-capsule.jar xxx.apk xxx.apk channel.txt` 命令行工具处理上面能成功安装的apk文件生成渠道包 -> 
安装渠道包  ->  INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by dkmeteor** [comment]
上述情况3   "v2SigningEnabled true" + packe
在 6.0设备上安装可通过
在 7.0上才会失败

**Comment by mcxiaoke** [comment]
稍后我验证一下

**Comment by mcxiaoke** [comment]
看了一下官方文档，确认V2签名模式会校验apk的sha256的值，修改apk后会无法安装，我更新一下文档

**Comment by dkmeteor** [comment]
@mcxiaoke 
具体文档在哪,我研究研究.

我就在N Preview介绍里看到这个v2签名,但是没找到具体原理或者流程 或者命令行工具介绍
如果有的话还可以试试,在unsigned apk 内写入渠道信息,再签名看是否可以通过验证.

**Comment by mcxiaoke** [comment]
https://developer.android.com/preview/api-overview.html#apk_signature_v2

**Comment by mcxiaoke** [comment]
`注意：如果您使用 APK Signature Scheme v2 签署您的应用，并对应用进行了进一步更改，则应用的签名将无效。 出于这个原因，请在使用 APK Signature Scheme v2 之前、而非之后使用 zipalign 等工具。`

**Comment by dkmeteor** [comment]
@mcxiaoke 

这个我看到了. 但是文档没有给出 如何调用`APK Signature Scheme v2 ` 给一个 unsigned apk 签名.
在这个机制下,渠道信息实际上要对 unsigned apk注入,然后再签名.

**Comment by mcxiaoke** [comment]
下个版本会增加V2签名检测和提示

**Comment by mcxiaoke** [comment]
1.0.6 released, fixed

**Comment by daiwenbo88** [comment]
不知道站主在吗 我使用Gradle配置打包的过程中 碰到了这异常 不知道能否提供解决的办法：
Configuration on demand is an incubating feature.
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:606)
        at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:572)
        at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:569)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
        at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:568)
        at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:565)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)

**Comment by mcxiaoke** [comment]
@daiwenbo88 看错误提示： 'java.lang.IllegalStateException: buildToolsVersion is not specified.' 这个与packer无关，检查下你的 build.gradle

**Comment by daiwenbo88** [comment]
嗯 我的工程gradle 使用的是classpath 'com.android.tools.build:gradle:2.0.0' 不知道是否跟这个有关系
另外 我的gradle中使用了
splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a', 'armeabi'
            universalApk false
        }
    }
分包 不知道这个是否能支持

**Comment by wooden1985** [comment]
我设置了 v2SigningEnabled false 但是还是用V2签名的 那是为什么？

**Comment by oyty** [comment]
同问啊，我的gradle版本是2.14.1， gradle tools版本是2.2.2， 在项目gradle  配置里面也加了v2SigningEnabled false， 因为我是python打渠道包，在项目内并没有引入任何依赖，但是打好了渠道包后，在android 7.0, 7.1上还是无法安装，求解？

**Comment by mcxiaoke** [comment]
@wooden1985 @oyty 刚刚测试完，渠道包安装没有问题

**Comment by HankZhang** [comment]
@oyty ,我也遇到了相同的问题，你的问题解决了吗？求分享

**Comment by oyty** [comment]
打包配置那个还是没作用，但是我把android studio版本降低了，这样就默认不用新的打包方式了，倒是一种解决方案

Life is too short to wait.

**Comment by mcxiaoke** [comment]
@oyty 我们的线上产品一直在使用，没有发现问题，建议你完整阅读一下ReadMe，检查一下配置和命令，还是不行的话，贴上你的build.gradle和打包命令行输出看看

**Comment by mcxiaoke** [comment]
@HankZhang 建议同上

**Comment by CongZ-github** [comment]
v2SigningEnabled false配置不生效的原因可能是因为用的是Build下边的Generate Signed APK来生成的apk，这样生成的apk并没有用到gradle中的签名配置，需要修改为用gradle命令生成apk禁用v2签名的配置就能生效了。

**Comment by daiwenbo88** [comment]
您好 给您发过相关邮件却未收到回复，我就最后想了解下 如果使用jar脚本打渠道包的话 那么在build.gradle中的：
        defaultConfig {
                    manifestPlaceholders = [JPUSH_APPKEY: "xxxxxxxxxx"]
        }
以上配置还会受到 “不支持修改AndroidManifest”的影响吗

**Comment by mcxiaoke** [comment]
@daiwenbo88 PackerNg不会修改APK的内容，不参与Gradle构建过程，所以不会影响你在 build.gradle 中的配置，具体实现原理可以看ReadMe

**Comment by androidzhangyu** [comment]
打出的包app-release-mm005.apk 。如果我不想要app-release-  ，该怎么解决了，大神

**Comment by mcxiaoke** [comment]
@androidzhangyu 看首页 **[插件配置说明]** 部分，使用`archiveNameFormat`自定义

**Comment by androidzhangyu** [comment]
谢谢，您说的是在as里面配置的么？我使用的是java -jar的方式，但是不知道怎么修改，我只想得到mm005.。

**Comment by mcxiaoke** [comment]
@androidzhangyu 暂时不支持，你自己写个脚本改吧

**Comment by androidzhangyu** [comment]
@mcxiaoke  好的谢谢。我使用python的时候出现ModuleNotFoundError: No module named 'apkinfo'  ，请问是什么原因造成的。麻烦大神了。

**Comment by mcxiaoke** [comment]
@androidzhangyu apkinfo.py在tools目录下，你copy过去，或者在tools目录下运行，还有，需要Python 2.x

**Comment by luxianyue** [comment]
总是提示这个错误：FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:apkAaaaaaRelease'.
> No such property: flavorName for class: SimpleTemplateScript11

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
怎么解决呢
