### ISSUE TITLE
打出来的包签名有问题啊

### ISSUE THREAD

**Issue by daixiansen** [mcxiaoke/packer-ng-plugin#32]
打出来的包签名有问题,为什么我这个属性   v2SigningEnabled false   设置上去报错,Error:Gradle DSL method not found: 'v2SigningEnabled()'  ,这是咋回事啊?

**Comment by mcxiaoke** [comment]
如果你没有针对 Android 7.0打包，不需要添加 v2SigningEnabled ；另外，升级到使用最新的1.0.6版

**Comment by daixiansen** [comment]
我是用的最新的1.0.6版本啊,但打出来的包签名就是有问题额.   方便我把demo发你帮我看看吗?谢谢!

**Comment by mcxiaoke** [comment]
@daixiansen 你发给我试试

**Comment by daixiansen** [comment]
我发你邮箱了,可以收到吧?

**Comment by daixiansen** [comment]
签名文件就在工程根目录 pack.jks ,密码之类的在 bulid.gradle 中都有配置的.



542978566@qq.com
 
发件人： 542978566@qq.com
发送时间： 2016-08-09 11:21
收件人： mcxiaoke/packer-ng-plugin
主题： Re: Re: [mcxiaoke/packer-ng-plugin] 打出来的包签名有问题啊 (#32)
麻烦帮忙看看,谢谢啦!



542978566@qq.com
 
发件人： Xiaoke Zhang
发送时间： 2016-08-09 11:18
收件人： mcxiaoke/packer-ng-plugin
抄送： daixiansen; Mention
主题： Re: [mcxiaoke/packer-ng-plugin] 打出来的包签名有问题啊 (#32)
@daixiansen 你发给我试试

**Comment by mcxiaoke** [comment]
@daixiansen 没收到，你重新发到这个邮箱试试？  mcxiaoke@live.com

**Comment by mcxiaoke** [comment]
附件下载比较慢，要不你贴一下 你的 build.gradle 和 完整的报错信息吧

**Comment by daixiansen** [comment]
1. 这是根目录的build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'

//        classpath "com.android.tools.build:gradle:2.2.0-alpha7"

        // add packer-ng
        classpath 'com.mcxiaoke.gradle:packer-ng:1.0.6'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

2. 这是项目的build.gradle  
apply plugin: 'com.android.application'
apply plugin: 'packer'

android {
    compileSdkVersion 23
    buildToolsVersion "24.0.1"

    defaultConfig {
        applicationId "daixiansen.packdemo"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    /*签名*/
    signingConfigs {
        debug {
            storeFile file("../pack.jks")
            storePassword '666666'
            keyAlias 'pack'
            keyPassword '666666'
        }
        release {
            storeFile file("../pack.jks")
            storePassword '666666'
            keyAlias 'pack'
            keyPassword '666666'
            // 如果要支持最新版的系统 Android N(7.0)
            // 这一行必须加，否则安装时会提示没有签名
            // 作用是只使用旧版签名，禁用V2版签名模式
//            v2SigningEnabled  false
        }
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.mcxiaoke.gradle:packer-helper:1.0.6'
}
3. 加这个了之后的报错信息:
 // 如果要支持最新版的系统 Android N(7.0)
            // 这一行必须加，否则安装时会提示没有签名
            // 作用是只使用旧版签名，禁用V2版签名模式
//            v2SigningEnabled  false
 Error:Gradle DSL method not found: 'v2SigningEnabled()'


542978566@qq.com
 
发件人： Xiaoke Zhang
发送时间： 2016-08-09 11:52
收件人： mcxiaoke/packer-ng-plugin
抄送： daixiansen; Mention
主题： Re: [mcxiaoke/packer-ng-plugin] 打出来的包签名有问题啊 (#32)
附件下载比较慢，要不你贴一下 你的 build.gradle 和 完整的报错信息吧

**Comment by mcxiaoke** [comment]
你的gradle版本是，如果用的是 ./gradlew 那么 gradle wrapper的版本号是？

**Comment by mcxiaoke** [comment]
问题找到了，除非满足下面的条件，否则不需要添加： v2SigningEnabled  false

1. 保证 gradle 版本 >= 2.14.1
2. 保证 andorid gradle plugin 版本 >=  2.2.0，目前是 2.2.0-alpha7

你的 gradle wrapper版本是 2.10.0, android gradle plugin 版本是  2.0.0 ，不需要添加  v2SigningEnabled  false

**Comment by daixiansen** [comment]
我把v2SigningEnabled false 代码有注销啊,没有添加.    然后打包没报错    全部打出来了,但是签名全部有问题额.

**Comment by daixiansen** [comment]
我把v2SigningEnabled false 代码有注释啊,没有添加. 然后打包没报错 全部打出来了,但是签名全部有问题额.

**Comment by mcxiaoke** [comment]
@daixiansen 我再看看

**Comment by mcxiaoke** [comment]
你的 buildTypes.release 没有指定 signingConfig，即使去掉Packer的配置打出来的apk也是没有签名的，与PackerNg无关

**Comment by daixiansen** [comment]
好的,这个签名问题解决了,但是又出现个新问题    集成后程序直接用编译器运行,启动不了app.

**Comment by mcxiaoke** [comment]
@daixiansen 你的问题与此项目无关，建议看文档或搜索解决

**Comment by daixiansen** [comment]
嗯嗯,好的
