### ISSUE TITLE
最新版本python脚本运行会有问题

### ISSUE THREAD

**Issue by c1024** [mcxiaoke/packer-ng-plugin#35]
最新版本python脚本运行会有问题。
https://github.com/mcxiaoke/packer-ng-plugin/blob/master/tools/PackerNg-1.0.7.py这里面
_check和_parse_args参数名不一致
运行会提示：
raceback (most recent call last):
  File "/Users/gxq/Desktop/androidcode/doublewhitecollar/packerNg.py", line 233, in <module>
    _check(**vars(args))
TypeError: _check() got an unexpected keyword argument 'marketfile'

**Comment by mcxiaoke** [comment]
thanks, fixed in https://github.com/mcxiaoke/packer-ng-plugin/commit/f4413bc394c1cc92fec73f0799f8ba3967a4641c
