### ISSUE TITLE
不支持split apk

### ISSUE THREAD

**Issue by markzhai** [mcxiaoke/packer-ng-plugin#37]
splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'x86' //, 'x86', 'armeabi-v7a', 'mips'
            universalApk false
        }
    }

使用了 splitspk，但是只打出了x86的渠道包

**Comment by mcxiaoke** [comment]
目前应该不支持，欢迎提pr

**Comment by czy1121** [comment]
那个 splits 貌似没啥用，要么全打包进去了，要么只有一个
下边这个可以
```
productFlavors {
    xxx {
        ndk {
            abiFilters "armeabi-v7a", 'arm64-v8a'
        }
    }
}
```

**Comment by markzhai** [comment]
@czy1121 跑题了吧。anyway，我们需要的就是只有一个的效果

**Comment by czy1121** [comment]
我还以为你希望输出的apk里有 'armeabi-v7a', 'x86' 但用splits 却只有x86

**Comment by mcxiaoke** [comment]
这样试试？

```
productFlavors {
    armv7a {
        ndk {
            abiFilters "armeabi-v7a",
    }

    x86 {
        ndk {
            abiFilters "x86",
    }
}
```

然后 

```
./gradlew -Pmarket=markets.txt clean apkArmv7aRelease apkX86Release
```
