### ISSUE TITLE
使用packer-ng-plugin无法生成渠道包

### ISSUE THREAD

**Issue by LouisLuo2016** [mcxiaoke/packer-ng-plugin#39]
用最新的版本1.0.7按照Readme文件配置下来，用命令gradlew -Pmarket=markets.txt clean assembleRelease只生成了release.apk文件，配置的渠道包没有生成，也没报任何错。我用的是win7，是不是有关系。
下载的PackerNg-1.0.7.jar这个包有问题，不能运行。

**Comment by mcxiaoke** [comment]
仔细看文档，是 `./gradlew -Pmarket=markets.txt clean apkRelease` 是 `apkRelease`

**Comment by LouisLuo2016** [comment]
然并卵，之前使用apkRelease时直接报错Task 'apkRelease' not found in root project
assembleRelease是我Gradle中的task
