### ISSUE TITLE
PackerNg工具只能在项目主工程中使用

### ISSUE THREAD

**Issue by alonelyshepherd** [mcxiaoke/packer-ng-plugin#40]
在子工程中加入
~~~
dependencies {
    compile 'com.mcxiaoke.gradle:packer-helper:1.0.7'
}
~~~
会提示找不到，加上 `apply plugin: 'packer'`后又提示`Cause: the android plugin must be applied`

有些情况下确实需要在子工程中获取当前渠道，希望能够支持

**Comment by mcxiaoke** [comment]
获取渠道只需要添加 compile 'com.mcxiaoke.gradle:packer-helper:1.0.7' ，并不需要配置其它gradle选项

**Comment by alonelyshepherd** [comment]
在子工程中加是不行的
