### ISSUE TITLE
使用命令行打包只能打一个么？

### ISSUE THREAD

**Issue by AlanCheen** [mcxiaoke/packer-ng-plugin#42]
尝试了一下
```
java -jar PackerNg-x.x.x.jar apkFile marketFile outputDir
```

marketFile 是个渠道列表文件，不过结果只能打出一个包，是现在还不支持么？

**Comment by mcxiaoke** [comment]
打包好的apk在你指定的outputDir目录里

**Comment by AlanCheen** [comment]
我尝试了 发现只打出了一个包


Xiaoke Zhang <notifications@github.com>于2016年9月21日周三 下午3:13写道：

**Comment by mcxiaoke** [comment]
@AlanCheen 刚测试，没问题

**Comment by AlanCheen** [comment]
奇怪 我也测试了 依然有问题

**Comment by AlanCheen** [comment]
对marketFile有什么要求吗？

**Comment by AlanCheen** [comment]
![](http://ww4.sinaimg.cn/large/98900c07gw1f83qxpt1n9j20ij0btgpg.jpg)

我把条件 结果 截了个图，麻烦你看看~

**Comment by AlanCheen** [comment]
是 market info 的关系么？

**Comment by AlanCheen** [comment]
尝试了一下 就是 market info 已经存在才有问题。

 那是不是不能用已经存在的包再打新的渠道包了？？？

**Comment by mcxiaoke** [comment]
@AlanCheen 目前不支持

**Comment by AlanCheen** [comment]
有计划做不？
