### ISSUE TITLE
Java代码中获取不到当前渠道号

### ISSUE THREAD

**Issue by wangfeihang** [mcxiaoke/packer-ng-plugin#45]
我在代码中这样使用PackerNg:
                final String market = PackerNg.getMarket(this);
                Toast.makeText(getActivity(), "market is :"+market, Toast.LENGTH_SHORT).show();
但是用java脚本生成的apk运行的时候
弹出的toast是“market is”没有渠道号信息。

**Comment by mcxiaoke** [comment]
打包时的输出信息贴一下
