### ISSUE TITLE
gradle tasks 显示的可用task没有apkDebug

### ISSUE THREAD

**Issue by StevenWT** [mcxiaoke/packer-ng-plugin#47]
集成到项目后，存在apkRelease命令，找不到apkDebug命令

**Comment by StevenWT** [comment]
本地构建的buildTypes有三种类型，debug,graydebug,release

**Comment by StevenWT** [comment]
* What went wrong:
Task 'apkDebug' not found in root project 'stock_android'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by mcxiaoke** [comment]
渠道打包仅针对debug以外的buildType

**Comment by StevenWT** [comment]
ok,thanks
