### ISSUE TITLE
为什么manifestMatcher = ['UMENG_CHANNEL','Promotion_Market']  这个属性不管用

### ISSUE THREAD

**Issue by challengemyself** [mcxiaoke/packer-ng-plugin#48]
packer {
    manifestMatcher = ['UMENG_CHANNEL','Promotion_Market']
}
配置了这个属性，然后运行命令打出来包之后，反编译apk，发现清单文件里面的
<meta-data
            android:name="UMENG_CHANNEL"
            android:value="UMENG_CHANNEL"/>
这个value，没有替换成相应各个market的值

**Comment by mcxiaoke** [comment]
替换manifest值用这个 https://github.com/mcxiaoke/gradle-packer-plugin
