### ISSUE TITLE
打包时候卡在building阶段

### ISSUE THREAD

**Issue by littleQia** [mcxiaoke/packer-ng-plugin#49]
公司其他同事用他的电脑打包会卡在Building88%阶段 报错为：
![iflv a nfn rl_os d t5](https://cloud.githubusercontent.com/assets/22090724/19585698/2df2124a-9781-11e6-8771-c81668f01f92.png)

**Comment by mcxiaoke** [comment]
看截图还没走到渠道打包这一步，建议你检查网络等其它配置
