### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by appledong** [mcxiaoke/packer-ng-plugin#5]
很好，经测试很快，不管多少渠道基本上都是一个包的时间，但是不知道这个框架兼不兼容当前的第三方sdk（第三方的sdk不可以在代码里设置的，只能读取manifest文件），该框架的原理是通过修改zip的数据进行渠道修改，没有涉及到manifest文件，会不会出现问题。

**Comment by mcxiaoke** [comment]
如果第三方SDK支持在代码里设置渠道的就可以，如果写死了从manifest文件里读取就不行
