### ISSUE TITLE
麻烦帮忙看看啊,谢谢

### ISSUE THREAD

**Issue by wangfanforever** [mcxiaoke/packer-ng-plugin#52]
我的环境是windows 8 ,jdk1.7,报错如下:
麻烦帮忙看看啊,谢谢
F:\AndroidStudioProjects\Packer>gradlew.bat -Pmarket=markets.txt clean archiveApkRelease
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/
2.14.1/userguide/gradle_daemon.html.
                                                                                 
FAILURE: Build failed with an exception.

* Where:
Build file 'F:\AndroidStudioProjects\Packer\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by mcxiaoke** [comment]
直接 gradlew.bat lean assembleRelease 看看有没有报错

**Comment by thearyong** [comment]
我遇到同样的问题，后来检查下终端的 jdk 环境，要和android studio打包的jdk一致。修改下本机的 jdk1.8就好了
