### ISSUE TITLE
支持微信的热修复tinker吗，

### ISSUE THREAD

**Issue by yingjinping** [mcxiaoke/packer-ng-plugin#53]
我是用 gradlew.bat clean apkRelease打出渠道包
gradlew.bat tinkerPatchRelease 打出了补丁包
结果release包补丁是生效的，build\archives下的渠道包，补丁包却失效
请问支持微信的热修复tinker吗？

**Comment by mcxiaoke** [comment]
没有直接支持，应该不冲突，你可以对照文档自己研究一下

**Comment by mcxiaoke** [comment]
邮件已回复

**Comment by yingjinping** [comment]
好的，谢谢。查下来是tinker 1.7.3已知的问题
MD5 verify would failed when generate small dex from unmodified dex on Art Device
