### ISSUE TITLE
Android 7.1上安装渠道包，报软件包损坏，无法安装

### ISSUE THREAD

**Issue by oyty** [mcxiaoke/packer-ng-plugin#57]
测试手机：Google Nexus 5X  7.1

**Comment by mcxiaoke** [comment]
用最新版，看ReadMe有说明，这里也有说: https://github.com/mcxiaoke/packer-ng-plugin/blob/master/compatibility.md

**Comment by oyty** [comment]
谢谢，自己没细心看说明。。

**Comment by oyty** [comment]
你好，我的gradle版本是2.14.1， gradle tools版本是2.2.2， 在项目gradle
 配置里面也加了v2SigningEnabled false，
因为我是python打渠道包，在项目内并没有引入任何依赖，但是打好了渠道包后，在android 7.0,
7.1上还是无法安装，签名不一致，貌似还是那个v2 配置无效，求解😭

Life is too short to wait.

**Comment by mcxiaoke** [comment]
@oyty 我再测试一下答复你

**Comment by mcxiaoke** [comment]
@oyty 刚刚测试完，在 7.1模拟器上安装没有问题

**Comment by wznshuai** [comment]
@oyty 你的问题解决了吗 我的也是加了v2SigningEnabled false 不起作用

**Comment by oyty** [comment]
我是在真机上测的，还是不行啊

Life is too short to wait.
