### ISSUE TITLE
渠道包获取不了

### ISSUE THREAD

**Issue by yatou252303** [mcxiaoke/packer-ng-plugin#62]
使用package_ng  导致线上umeng统计渠道获取不了渠道包的。想问下，有多大概率拿不到渠道包

**Comment by mcxiaoke** [comment]
友盟需要在代码里手动设置渠道，具体方法请看友盟的文档

**Comment by yatou252303** [comment]
找到原因了，是360加固导致的问题。

**Comment by mcxiaoke** [comment]
可以先用原始apk执行加固，加固之后的apk再用脚本打渠道包
