### ISSUE TITLE
window 使用命令行打 360渠道出现渠道乱码现象

### ISSUE THREAD

**Issue by yatou252303** [mcxiaoke/packer-ng-plugin#63]
window 系统  使用命令行打渠道，渠道会出现乱码现象。确定编码是 utf_8 的。

Apk File: F:\360\2.5.1.apk
Market File: F:\360\markets.txt
Output Dir: F:\360\outputDir
Generating apk 2.5.1-锘?360dev.apk
[Success] All 1 apks saved to F:\360\outputDir

**Comment by yatou252303** [comment]
我用Helper 这个类的api打渠道，然后读出来是正确 ，还有一个问题是 使用packet_ng 打渠道会增加1MB 左右的额外大小？  麻烦解答一下

**Comment by mcxiaoke** [comment]
@yatou252303 

1. 乱码是Windows的编码问题
2. 不会增加大小

**Comment by yatou252303** [comment]
现在我们暂时用 Helper 类打包。找到问题再进行更正。非常感谢
279642707@qq.com
 
发件人： Xiaoke Zhang
发送时间： 2016-12-23 17:29
收件人： mcxiaoke/packer-ng-plugin
抄送： mrchao; Mention
主题： Re: [mcxiaoke/packer-ng-plugin] window 使用命令行打 360渠道出现渠道乱码现象 (#63)
@yatou252303
乱码是Windows的编码问题
不会增加大小
