### ISSUE TITLE
关于修改AndroidManifest

### ISSUE THREAD

**Issue by daiwenbo88** [mcxiaoke/packer-ng-plugin#66]
你好 有个问题不太明确
 这个打包方式不支持修改AndroidManifest？
 如果我的AndroidManifest中有以下：
  <meta-data name="xxxx" value="NAME_VALUE"></meta-data>
如果我这样配置支持吗：
  defaultConfig {
            manifestPlaceholders[NAME_VALUE :xxxxxxxxxx]
    }

**Comment by mcxiaoke** [comment]
不支持
