### ISSUE TITLE
渠道包通过mac QQ传输后，渠道被篡改

### ISSUE THREAD

**Issue by xueleitt** [mcxiaoke/packer-ng-plugin#67]
版本1.0.2，打好渠道包之后，通过QQ直接把APK文件发给对方，收到之后发现渠道变成了另外一个，请问是怎么回事？

**Comment by mcxiaoke** [comment]
建议你仔细检查一下，或者压缩后发送，应该和打包工具没关系。

**Comment by xueleitt** [comment]
umeng的方式没有这种问题

**Comment by mcxiaoke** [comment]
没有收到类似反馈；与打包工具无关；如果实在找不到原因建议你压缩apk后再发送试试

**Comment by xueleitt** [comment]
压缩后可以，我xiaomi渠道包，发送给别人变成了huawei，渠道命名有要求么？aa-b,带横线的渠道可以么
