### ISSUE TITLE
电脑管家报毒

### ISSUE THREAD

**Issue by 360625368** [mcxiaoke/packer-ng-plugin#68]
电脑管家报毒啊兄弟，虽然说你这东西用起来确实爽，但是电脑管家报毒啊，这样不好吧？

**Comment by mcxiaoke** [comment]
那就别用

**Comment by xushaun** [comment]
用了大半年了，之前不报毒，但是这几天好像腾讯手机管家报毒了，用了没渠道的包不报毒，打了渠道报毒了
