### ISSUE TITLE
It doesn't work on android 7.1.1, Nexus 5x.

### ISSUE THREAD

**Issue by whoooami** [mcxiaoke/packer-ng-plugin#69]
When I use packer-ng[1.0.7/1.0.8] generate apk, I can't install it in my phone. 
The error msg：
App not installed.
The package appears to be corrupt.

**Comment by mcxiaoke** [comment]
read [this](https://github.com/mcxiaoke/packer-ng-plugin#特别提示)

**Comment by whoooami** [comment]
Thanks for reply. Did't you mean the "v2SigningEnabled false", My Android Gradle Plugin id2.14.1.
still need add this to gradle file?

**Comment by whoooami** [comment]
Thx, You saved my day.
