### ISSUE TITLE
能否在 archiveNameFormat 输出文件格式中添加自定义的渠道名称

### ISSUE THREAD

**Issue by ebnbin** [mcxiaoke/packer-ng-plugin#70]
目前 `archiveNameFormat` 中的 `flavorName` 是渠道 id，markets.txt 配置文件中一般是 
```
123#豌豆荚
456#安智市场
789#应用宝
```
不支持在输出文件名中添加自定义的渠道名（注释后面的中文渠道名），这样发布市场时需要通过渠道 id 去找对应的市场渠道名称，比较麻烦也容易出错，能不能在配置中添加这个选项

**Comment by mcxiaoke** [comment]
可以看看这里的方法 https://github.com/mcxiaoke/packer-ng-plugin/issues/19

**Comment by ebnbin** [comment]
哦哦谢谢作者，刚刚看到了，另外，我想到一个比较 hack 的方式解决这个问题，就是在 market.txt 中这么定义：
```
123-豌豆荚
456-安智市场
789-应用宝
```
然后在使用 `PackerNg.getMarket(context);` 读取渠道时，格式化读取到的字符串，取 `-` 之前的字符串作为渠道 id，也能实现效果，因为懒(bu)得(hui)写重命名文件的脚本，所以就这么取巧了。
我想确认一下这种方式是否不会有问题，我自己试过是可行的，我看了项目中的 market.txt 文件，应该这种打包方式是支持中文作为渠道 id 的吧？？

**Comment by ebnbin** [comment]
主要是中文编码方面，会不会有问题？

**Comment by mcxiaoke** [comment]
中文可能会有问题，渠道号只是一个识别符，你用数字英文拼音都行，实在不行用一个表格记录一下也行，只要能找到对应关系就行
