### ISSUE TITLE
疑问：获取sourceDir反射publicSourceDir的原因

### ISSUE THREAD

**Issue by shwenzhang** [mcxiaoke/packer-ng-plugin#71]
这里不使用packageInfo.sourceDir的原因是什么？在7.0之后，我们可能要hack掉publicSourceDir这个字段

![image](https://cloud.githubusercontent.com/assets/8335303/23459078/dcc64a1c-feb9-11e6-94f0-9a42197e19cc.png)

**Comment by mcxiaoke** [comment]
helper是个纯Java库，不依赖Android，命令行工具也要使用

**Comment by shwenzhang** [comment]
publicSourceDir 在7.0以后 webview使用的是这边这个字段，所有tinke热修复r需要反射这个字段。如果使用packer-ng-plugin，补丁之后就读不到渠道信息了。
或者我试试把基准包的comment也添加到补丁包中把

**Comment by mcxiaoke** [comment]
我可以更新一个版本，优先使用sourceDir的值，但很多使用这个工具的用户并不经常更新

**Comment by shwenzhang** [comment]
嗯，我这边也试一下把comment也拷贝过去。主要是因为之前在tinker推荐了packer-ng-plugin 作为渠道包方案

**Comment by mcxiaoke** [comment]
1.0.9已发布 https://github.com/mcxiaoke/packer-ng-plugin/commit/07ab81fb1d9bb9ee2b6c032d071b10cad3c64840

**Comment by mcxiaoke** [comment]
fixed
