### ISSUE TITLE
如何用命令行设置v2SigningEnabled

### ISSUE THREAD

**Issue by kris520** [mcxiaoke/packer-ng-plugin#73]
./gradlew -Pmarket=test_channels.txt clean apkRelease -Pandroid.injected.signing.store.file=$KEYFILE -Pandroid.injected.signing.store.password=$STORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASSWORD

加上下面两种都不好使
-Pandroid.injected.signing.v2SigningEnabled=false
或者
-Pandroid.injected.signing.v2.signingEnabled=false

**Comment by mcxiaoke** [comment]
不太清楚，你可以看Gradle的文档
