### ISSUE TITLE
请教一下 如何在打完渠道包之后去验证 这个包是否包含有渠道信息了呢

### ISSUE THREAD

**Issue by GithubOfJay** [mcxiaoke/packer-ng-plugin#75]

**Comment by mcxiaoke** [comment]
看文档，命令行工具可以验证，也可以添加调试代码验证

**Comment by GithubOfJay** [comment]
情况是这样的 最近umeng的渠道统计结果 出现大量unknow的渠道，以前几个版本也都用的是咱们这个框架是没有这个问题的  然后我需要验证发出去的包是不是每个都含有渠道信息了 发出去的包我是没有加打印渠道信息的log代码的，然后我也看了文档 还是没找到直接去查看apk文件的渠道信息，希望能告知，挺急的 谢谢了。

**Comment by mcxiaoke** [comment]
命令行脚本可以显示渠道信息

**Comment by GithubOfJay** [comment]
你看我 是不是理解的不对   我看到的脚本 应该是在打包过程中会显示 渠道信息   
现在我是有一个现成的 apk 想看看这个 apk有没有渠道信息   其实这么做还有一部分原因 也是想验证是不是apk被反编译了导致的没有渠道信息的活跃用户亦或者是 umeng的问题 
所以 可以明确说明是哪个脚本么  实在是没理解您的意思啊  不好意思

**Comment by mcxiaoke** [comment]
Java脚本

java -jar PackerNg-x.x.x.jar apkFile marketFile outputDir

Python脚本

python PackerNg-x.x.x.py [file] [market] [output] [-h] [-s] [-t TEST]

你运行一下就知道了，可以打包，也可以显示APK的信息

**Comment by GithubOfJay** [comment]
python PackerNg-1.0.9.py -s 1.apk
Traceback (most recent call last):
  File "PackerNg-1.0.9.py", line 13, in <module>
    from apkinfo import APK
  File "C:\Users\Jay_zhao\Desktop\packer-ng-plugin-master\tools\apkinfo.py", line 306
    except Exception, e:
                    ^
SyntaxError: invalid syntax
我的会报导入apkinfo的错  是python版本的问题么 我的是3.6.1的

**Comment by mcxiaoke** [comment]
是，需要Python 2.x

**Comment by GithubOfJay** [comment]
好的 已经查看到了 万分感谢。。
