### ISSUE TITLE
2.0 的是要16 号才能用么？

### ISSUE THREAD

**Issue by hyr0318** [mcxiaoke/packer-ng-plugin#77]
Error:Could not find com.mcxiaoke.packer-ng:plugin:2.0.0.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/mcxiaoke/packer-ng/plugin/2.0.0/plugin-2.0.0.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/mcxiaoke/packer-ng/plugin/2.0.0/plugin-2.0.0.jar
    https://jcenter.bintray.com/com/mcxiaoke/packer-ng/plugin/2.0.0/plugin-2.0.0.pom
    https://jcenter.bintray.com/com/mcxiaoke/packer-ng/plugin/2.0.0/plugin-2.0.0.jar
Required by:
    project :

**Comment by mcxiaoke** [comment]
请只关注master分支的情况，目前2.0.0还在开发中，还没合并到master分支，预计6月底正式发布

**Comment by hyr0318** [comment]
@mcxiaoke  好的。那我到时候再换到2.0  。另外还有个问题，用1.9 的命令行方式打渠道包的方式 有的手机会获取不到渠道，是什么原因额？

**Comment by mcxiaoke** [comment]
@hyr0318 先用命令行脚本验证渠道包确实写入了渠道信息；如果没问题，还有一种可能是，可能有特殊的一些手机会无法读取应用的 apk 文件

**Comment by walterFeng** [comment]
如何给apkRelease完成后添加自定义task？
```
    task iDependOnAssembleFlavor1Release << {
        println 'I need apkRelease to run before me.'
    }
    tasks.whenTaskAdded { task ->
        if (task.name == 'apkRelease') {
            iDependOnAssembleFlavor1Release.dependsOn(task)
        }
    }
```
@mcxiaoke这样写不管用，请指教

**Comment by mcxiaoke** [comment]
@walterFeng 测试没问题：

运行
```shell
./gradlew iDependOnAssembleFlavor1Release -Pmarket=markets.txt
```

输出

```
......
......
......
PackerNg Build Successful!
:app:apkRelease
:app:iDependOnAssembleFlavor1Release
I need apkRelease to run before me.

BUILD SUCCESSFUL
```

**Comment by mcxiaoke** [comment]
@walterFeng 如果你是想在 apkRelease的最后做些事，可以这样：

```
task someTask << {
    println 'I need apkRelease to run before me.'
}
tasks.whenTaskAdded { task ->
    if (task.name == 'apkRelease') {

        task.doLast {
            someTask.execute()
            println 'do someThing at last on task apkRelease.'
        }
    }
}
```

测试：

```
PackerNg Build Successful!
:app:apkRelease
I need apkRelease to run before me.
do someThing at last on task apkRelease.

BUILD SUCCESSFUL
```

**Comment by walterFeng** [comment]
@mcxiaoke 可以用，非常感谢！

**Comment by mcxiaoke** [comment]
2.0.0版已发布

**Comment by hyr0318** [comment]
@mcxiaoke  我打包之后，好像就只能获取到默认设置的应用宝渠道，其他的渠道好像都没有获取到额？
另外2.0 的打包，如果要使用加固，还是和原来的一样先加固，再用命令行打渠道包再签名这个步骤么？

**Comment by mcxiaoke** [comment]
@hyr0318 1. 看文档检查一下你的配置，2. 应该是需要先加固，你可以测试一下

**Comment by hyr0318** [comment]
@mcxiaoke  2.0 的脚本打包怎么用额？ 和之前完全不一样额？ 应该怎么操作额？

**Comment by mcxiaoke** [comment]
@hyr0318 README写得很详细了

**Comment by hyr0318** [comment]
@mcxiaoke  原来的命令有指定apk 的路径和 输出目录路径 和渠道信息文件的路径，2.0 的命令 没有额。我需要把需要打渠道的apk放在什么目录下么？

**Comment by hyr0318** [comment]
@mcxiaoke  packer-ng generate --channels=@channels.txt --output=build/archives app.apk
这个意思是把app.apk 和channels.txt放在tool的目录下，执行命令就行了么？
