### ISSUE TITLE
360和腾讯云-乐固加固后，无法使用脚本添加渠道信息

### ISSUE THREAD

**Issue by passionli** [mcxiaoke/packer-ng-plugin#80]
1.使用Packer 2.0.0的版本对APK进行V2签名打包后，使用jar脚本可以看到输出已签名和具体的渠道号。

2.使用360加固对以上包进行加固和自动签名（不确定360是使用V2还是V1签名）后，再使用jar脚本generate 参数进行写入渠道好数据，输出错误：

Error: Invalid Signature: XXXX

看样子像是这些第三方加固的签名数据不对造成的，但是一时也没想到好的解决方案。

3.请问是否确认过2.0.0版本加固后依然可以写入渠道信息？

3Q.

**Comment by mcxiaoke** [comment]
第三方加固破坏了原有的V2签名，你需要先签名，然后再用PackerNg写入渠道信息

**Comment by talentju** [comment]
我试过了，360加固完，下载下来的apk是没有签名的，要先签名再用脚本写入渠道，而且不要使用360提供的签名工具签名，那个工具只有V1的。

**Comment by mcxiaoke** [comment]
close
