### ISSUE TITLE
No such property: flavorName for class: SimpleTemplateScript

### ISSUE THREAD

**Issue by Heart2009** [mcxiaoke/packer-ng-plugin#82]
./gradlew clean apkGoogleRelease 

============================================================
PackerNg - https://github.com/mcxiaoke/packer-ng-plugin
============================================================
Variant: GoogleRelease
Input: xxx/app/build/outputs/apk/app-xxx-release.apk
Output: xxx/build/apks/talicai
Channels: [xiaomi meizu lianxiang baidu letv ppzhushou yingyongbao google huawei m360 oppo yingyonghui smartisan vivo]
:newapp:apkGoogleRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:apkGoogleRelease'.
> No such property: flavorName for class: SimpleTemplateScript4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by mcxiaoke** [comment]
改成 `flavor` ，文档有误，稍后修正

**Comment by Heart2009** [comment]
请问大侠哪里改成flavor呢 @mcxiaoke

**Comment by mcxiaoke** [comment]
@Heart2009 archiveNameFormat

**Comment by Heart2009** [comment]
ok

**Comment by DRPrincess** [comment]
@mcxiaoke  你的文档现在还没修正哦
