### ISSUE TITLE
v2SigningEnabled v2签名的问题

### ISSUE THREAD

**Issue by easternHong** [mcxiaoke/packer-ng-plugin#85]
> 
v2SigningEnabled false   使用jar,导处渠道包提示Error: Invalid Signature

> 
v2SigningEnabled true   使用jar,导出渠道包成功,但是 PackerNg.getMarket(ContextUtils.getContext()) 为空. 跟踪发现抛了异常 `throw new MarketNotFoundException("Zip comment magic bytes not found");`

**Comment by mcxiaoke** [comment]
看文档，plugin和helper版本号要一致，都要用2.0.0版，新版获取渠道的方法是 `PackerNg.getChannel(Context)`
