### ISSUE TITLE
gradlew clean apkRelease后项目R文件丢失

### ISSUE THREAD

**Issue by jan27th** [mcxiaoke/packer-ng-plugin#88]
记得原先有个Issues 实在找不到了 ，
执行命令行打包完成后，R文件就没了

**Comment by mcxiaoke** [comment]
本工具不参与编译过程，只会修改最终生成的apk文件，不会影响R文件

**Comment by clipperL** [comment]
奇怪了。我今天也发现执行完gradlew clean apkRelease后，R文件丢失。
