### ISSUE TITLE
 Error:Could not find property 'versionName' on com.mcxiaoke.packer.ng.PackerNgExtension_Decorated@69f4f0fc

### ISSUE THREAD

**Issue by loody** [mcxiaoke/packer-ng-plugin#9]
在配置输出目录这些值取不到是怎么回事？比如${versionName}
报错： Error:Could not find property 'versionName' on com.mcxiaoke.packer.ng.PackerNgExtension_Decorated@69f4f0fc.

这是我的配置代码：

packer {
        archiveOutput = file(new File(rootProject.getRootDir().getAbsolutePath() + "/app/build/outputs", "v${versionName}_${buildTime}"))
    }

**Comment by mcxiaoke** [comment]
${versionName}这些变量只适用于 archiveNameFormat ，archiveOutput是输出目录，写目录路径即可
