### ISSUE TITLE
Could not find com.android.tools.build:gradle:3.0.0-beta4.

### ISSUE THREAD

**Issue by xiangxm** [mcxiaoke/packer-ng-plugin#90]
Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-beta4/gradle-3.0.0-beta4.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-beta4/gradle-3.0.0-beta4.jar
     Required by:
         project : > com.mcxiaoke.packer-ng:plugin:2.0.0
 更新到最新的gradle3.0.0后就无法编译了，

**Comment by mcxiaoke** [comment]
错误信息不是很清楚吗： `Could not find com.android.tools.build:gradle:3.0.0-beta4`

**Comment by xiangxm** [comment]
恩，解决了，配置出现问题了，
