### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by taofaqi** [mcxiaoke/packer-ng-plugin#91]
:app:apkRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:apkRelease'.
> APK Signature Scheme v2 verify failed: 'F:\bocai\app\build\outputs\apk\app-release-unsigned.apk'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by mcxiaoke** [comment]
错误信息很清楚，你的apk没有签名
