### ISSUE TITLE
与1.x版本不兼容么

### ISSUE THREAD

**Issue by godlikewangjun** [mcxiaoke/packer-ng-plugin#98]
2.0版本取1.x版本的渠道取不到

**Comment by mcxiaoke** [comment]
文档有说明，不兼容，plugin 和 helper 的版本号需要保持一致

**Comment by godlikewangjun** [comment]
现在有个需求是判断渠道包，之前是1.x打的包，2.0版本是取的到之前1.x版本打的是哪个渠道包是吗？
