### ISSUE TITLE
Error: Invalid Signature 2.0

### ISSUE THREAD

**Issue by godlikewangjun** [mcxiaoke/packer-ng-plugin#99]
一个从市场上下的包，2.0的打包是Error: Invalid Signature 2.0错误，1.x打包没有错误但是安装失败。是什么原因？

**Comment by mcxiaoke** [comment]
信息太少，无法判断，请仔细阅读文档

**Comment by godlikewangjun** [comment]
命令打包的 用1.0.9打包来疯直播，安装报 [INSTALL_FAILED_INVALID_APK]。这是什么原因造成的，还是用的7z压缩的，这个打包不支持

**Comment by mcxiaoke** [comment]
打包工具肯定是没问题的，给出测试用的apk，命令行打包输出的信息，还有打包后的apk，我帮你看一下

**Comment by mcxiaoke** [comment]
打包工具1.x是写入zip的注释部分, 2.x是写入zip的cd部分，7z是不支持的

**Comment by godlikewangjun** [comment]
![image](https://user-images.githubusercontent.com/7495222/30893656-05f606c2-a372-11e7-8cff-fe943f5efa70.png)
apk包太大传不上来这是需要打包的apk链接http://dow.handzb.com/zreanimage/app/install/201709/Lfzb_Zw_0914.apk

**Comment by mcxiaoke** [comment]
```
unzip -z Lfzb_Zw_0914.apk
Archive:  Lfzb_Zw_0914.apk
ykpid_3550325730_2%7C170%7C84959%7C0____ykchannelid_10021308
```

你这个apk已经有渠道信息了，comments如上，不能重新写入

使用 `zip -z Lfzb_Zw_0914.apk` 去掉原有的comments之后，再用PackerNg打包，安装是没有问题的

```
adb install -r out2/Lfzb_Zw_0914-Google_Market.apk
out2/Lfzb_Zw_0914-Google_Market.apk: 1...d. 4.5 MB/s (42860942 bytes in 9.141s)
	pkg: /data/local/tmp/Lfzb_Zw_0914-Google_Market.apk
Success
```

**Comment by godlikewangjun** [comment]
好的 谢谢，注释是可以追加吗？像现在这种情况之前注释里面有些信息了。

**Comment by godlikewangjun** [comment]
我就觉得这个包，只要注释变了就安装不起，有点刁刁的

**Comment by mcxiaoke** [comment]
本工具不支持追加和替换，你可以自行去掉，然后再打渠道包
